server:
  port: 8888

spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: 127.0.0.1
  server:
    enable-self-preservation: true

  client:
    register-with-eureka: false
    fetch-registry: false


